# Generated by Django 3.2.14 on 2022-08-02 14:00

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.models.access_policy


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_auto_20220802_1312'),
        ('container', '0032_upload_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerRemoteConfig',
            fields=[
                ('remoteconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='container_containerremoteconfig', serialize=False, to='core.remoteconfig')),
            ],
            options={
                'permissions': [('manage_roles_containerremoteconfig', 'Can manage role assignments on container remote config')],
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.remoteconfig', pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
    ]
